remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: [Cascaded-ViT]
description: |
  Cascaded Chunk-FeedForward and Cascaded Group Attention Vision Transformer <br><br>
  Srivathsan Sivakumar, Faisal Z. Qureshi
show_downloads: [true]